name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access to Server, Remove Docker Containers, Build Docker Image, Run Docker Container
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.SERVER_ADDRESS }} "
          echo ✅ SSH connection successful &&
          echo ✅ Pulling from GitHub &&
          git pull &&
          running_containers=$(docker ps -q --filter ancestor=sklad_front) &&
          if [ -n \"$running_containers\" ]; then
          echo ✅ Stopping and removing running containers &&
          docker stop $running_containers &&
          docker rm $running_containers
          fi &&
          echo ✅ Building Docker Image &&
          docker build -t sklad_front . &&
          echo ✅ Running Docker Container &&
          docker run -d -p 80:3000 -p 443:443 --name sklad_front sklad_front &&
          echo ✅ Deployed successfully &&
          exit"
