name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/sklad_front:latest .
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/sklad_front:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Docker container on remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/sklad_front:latest
          docker stop sklad_front || true
          docker rm sklad_front || true
          docker run -d --name sklad_front -p 80:80 ghcr.io/${{ secrets.GHCR_USERNAME }}/sklad_front:latest
EOF
